Renamed all occurrences of yakuake to yakuaketwo

diff --git a/yakuaketwo-session b/yakuaketwo-session
--- a/yakuaketwo-session
+++ b/yakuaketwo-session
@@ -1,29 +1,29 @@
 #!/bin/bash
 #
-# yakuake-session - A script to create new yakuake sessions from command-line.
+# yakuaketwo-session - A script to create new yakuaketwo sessions from command-line.
 #
 # Copyright 2010-2013 Jesús Torres <aplatanado@gulic.org>
 #
-# yakuake-session comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
+# yakuaketwo-session comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions; see COPYING for details.
 #
 
-type -P yakuake &> /dev/null
+type -P yakuaketwo &> /dev/null
 if [ "$?" != 0 ]; then
-  echo "$(basename $0): error: yakuake is not installed" 1>&2
+  echo "$(basename $0): error: yakuaketwo is not installed" 1>&2
   exit 5
 fi
 
 function getcomm {
   type -P qdbus &> /dev/null && \
-    qdbus 2> /dev/null | grep -q org.kde.yakuake
+    qdbus 2> /dev/null | grep -q org.kde.yakuaketwo
   if [[ "$?" == 0 ]]; then
     echo dbus
     return
   fi
   type -P dcop &> /dev/null && \
-    dcop 2> /dev/null | grep -q yakuake
+    dcop 2> /dev/null | grep -q yakuaketwo
   if [[ "$?" == 0 ]]; then
     echo dcop
     return
@@ -35,20 +35,20 @@ function getcomm {
 # DBUS
 
 function dbus_addsession {
-  qdbus org.kde.yakuake /yakuake/sessions addSession > /dev/null
+  qdbus org.kde.yakuaketwo /yakuaketwo/sessions addSession > /dev/null
 }
 
 function dbus_runcommand {
-  qdbus org.kde.yakuake /yakuake/sessions runCommand "$1" > /dev/null
+  qdbus org.kde.yakuaketwo /yakuaketwo/sessions runCommand "$1" > /dev/null
 }
 
 function dbus_hasinterface {
-  qdbus org.kde.yakuake /yakuake/MainWindow_1 Introspect | grep -F "<interface name=\"$1\">"
+  qdbus org.kde.yakuaketwo /yakuaketwo/MainWindow_1 Introspect | grep -F "<interface name=\"$1\">"
 }
 
 function dbus_settitle {
-  id=$(qdbus org.kde.yakuake /yakuake/sessions sessionIdList | tr , "\n" | sort -g | tail -1 | tr -d '\n')
-  qdbus org.kde.yakuake /yakuake/tabs setTabTitle "$id" "$1" 
+  id=$(qdbus org.kde.yakuaketwo /yakuaketwo/sessions sessionIdList | tr , "\n" | sort -g | tail -1 | tr -d '\n')
+  qdbus org.kde.yakuaketwo /yakuaketwo/tabs setTabTitle "$id" "$1" 
 }
 
 function dbus_showwindow {
@@ -58,9 +58,9 @@ function dbus_showwindow {
   else
     interface="org.qtproject.Qt.QWidget"
   fi
-  ws=$(qdbus org.kde.yakuake /yakuake/MainWindow_1 Get $interface visible)
+  ws=$(qdbus org.kde.yakuaketwo /yakuaketwo/MainWindow_1 Get $interface visible)
   if [[ $? -eq 0 && "$ws" == "false" ]]; then
-    qdbus org.kde.yakuake /yakuake/window toggleWindowState > /dev/null
+    qdbus org.kde.yakuaketwo /yakuaketwo/window toggleWindowState > /dev/null
   fi
 }
 
@@ -72,17 +72,17 @@ function dcop_settitle {
 }
 
 function dcop_addsession {
-  dcop yakuake DCOPInterface slotAddSession > /dev/null
+  dcop yakuaketwo DCOPInterface slotAddSession > /dev/null
 }
 
 function dcop_runcommand {
-  dcop yakuake DCOPInterface slotRunCommandInSession "$1" > /dev/null
+  dcop yakuaketwo DCOPInterface slotRunCommandInSession "$1" > /dev/null
 }
 
 function dcop_showwindow {
-  ws=$(dcop yakuake yakuake-mainwindow#1 visible)
+  ws=$(dcop yakuaketwo yakuaketwo-mainwindow#1 visible)
   if [[ "$?" == 0 && "$ws" == false ]]; then
-    dcop yakuake DCOPInterface slotToggleState > /dev/null
+    dcop yakuaketwo DCOPInterface slotToggleState > /dev/null
   fi
 }
 
@@ -111,7 +111,7 @@ Options:
   --hold, --noclose         Do not close the session automatically when the command ends.
   -p <property=value>       Change the value of a profile property (only for KDE 4).
   -e <cmd>                  Command to execute.
-  -q                        Do not open yakuake window.
+  -q                        Do not open yakuaketwo window.
   -t <title>                Set the title of the new tab
 
 Arguments:
@@ -140,7 +140,7 @@ for arg do args="$args '$arg'" ; done
 
 comm=$(getcomm)
 if [[ "$comm" == none ]]; then
-  yakuake || exit 2
+  yakuaketwo || exit 2
   comm=$(getcomm)
   if [[ "$comm" == none ]]; then
     exit 3
